// @dignity/shared-types — enums
// Mirror of Prisma enums + additional application-level enums

export enum UserRole {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER",
  TREASURY_OFFICER = "TREASURY_OFFICER",
  MARKET_OPS_OFFICER = "MARKET_OPS_OFFICER",
  INVESTOR_RELATIONS = "INVESTOR_RELATIONS",
  AUDITOR = "AUDITOR",
  MARKET_MAKER = "MARKET_MAKER",
  INVESTOR = "INVESTOR",
  PUBLIC = "PUBLIC",
}

export enum KycStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  SUSPENDED = "SUSPENDED",
}

export enum TokenStatus {
  PLANNED = "PLANNED",
  DRAFT = "DRAFT",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  REDEEMED = "REDEEMED",
  TERMINATED = "TERMINATED",
}

export enum ReserveAssetClass {
  GOLD_BULLION = "GOLD_BULLION",
  GOLD_ETF = "GOLD_ETF",
  SILVER_BULLION = "SILVER_BULLION",
  PLATINUM = "PLATINUM",
  PALLADIUM = "PALLADIUM",
  CASH_USD = "CASH_USD",
  CASH_EUR = "CASH_EUR",
  TREASURY_BILL = "TREASURY_BILL",
  MONEY_MARKET = "MONEY_MARKET",
  OTHER = "OTHER",
}

export enum AttestationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  VERIFIED = "VERIFIED",
  SUPERSEDED = "SUPERSEDED",
  REVOKED = "REVOKED",
}

export enum OtcRfqStatus {
  OPEN = "OPEN",
  QUOTED = "QUOTED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  SETTLED = "SETTLED",
  CANCELLED = "CANCELLED",
}

export enum CircuitBreakerTrigger {
  NAV_DEVIATION = "NAV_DEVIATION",
  SPREAD_BREACH = "SPREAD_BREACH",
  VOLUME_SPIKE = "VOLUME_SPIKE",
  PRICE_ANOMALY = "PRICE_ANOMALY",
  LIQUIDITY_GAP = "LIQUIDITY_GAP",
  MANUAL_HALT = "MANUAL_HALT",
}

export enum AuditEventCategory {
  AUTH = "AUTH",
  KYC = "KYC",
  TOKEN_ACTION = "TOKEN_ACTION",
  COMPLIANCE = "COMPLIANCE",
  TREASURY = "TREASURY",
  RESERVE = "RESERVE",
  ATTESTATION = "ATTESTATION",
  MARKET_OPS = "MARKET_OPS",
  SYSTEM = "SYSTEM",
  ADMIN_ACTION = "ADMIN_ACTION",
}

// Application-level (not persisted, UI-only)
export enum DataSourceLabel {
  DEMO = "DEMO",
  LIVE = "LIVE",
  CACHED = "CACHED",
  STALE = "STALE",
}

export enum AlertSeverity {
  INFO = "INFO",
  WARN = "WARN",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL",
}
